//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoDono.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTADOR
    {
        public Nullable<int> Totaldotados { get; set; }
        public Nullable<int> TotalDisposiçao { get; set; }
        public Nullable<int> ToatalTratamento { get; set; }
        public int id { get; set; }
    }
}
