//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoDono.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DENUNCIA
    {
        public int IDD { get; set; }
        public string Denunciante { get; set; }
        public string TextoDenuncia { get; set; }
        public string Email { get; set; }
        public string CEP { get; set; }
        public string TipoLogradouro { get; set; }
        public string NomeLogradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public System.DateTime DataDenuncia { get; set; }
        public Nullable<System.DateTime> DataResposta { get; set; }
    }
}
