//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoDono.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int IDF { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Opiniao { get; set; }
        public string Feedback { get; set; }
    }
}
