//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoDono.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONTROLE
    {
        public int IDC { get; set; }
        public int IDPet { get; set; }
        public string NomePet { get; set; }
        public int IDDoador { get; set; }
        public string Doador { get; set; }
        public int IDDono { get; set; }
        public string Dono { get; set; }
        public Nullable<System.DateTime> DataAdocao { get; set; }
        public string Statu { get; set; }
    }
}
