//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoDono.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DENUNCIA
    {
        public string Email { get; set; }
        public string Denunciante { get; set; }
        public string TextoDenuncia { get; set; }
        public System.DateTime DataDenuncia { get; set; }
    }
}
